BEGIN TRANSACTION;
-- DROP TABLE room;
-- DROP TABLE user;
CREATE TABLE IF NOT EXISTS "user" (
	"UUID"	TEXT NOT NULL UNIQUE,
	"CreationDate"	TEXT DEFAULT CURRENT_TIMESTAMP,
	"LastSeenDate"	TEXT,
	"Name"	TEXT,
	"Avatar"	TEXT,
	PRIMARY KEY("UUID")
);
CREATE TABLE IF NOT EXISTS "room" (
	"PublicUrl"	TEXT NOT NULL,
	"IsActive"	INTEGER NOT NULL DEFAULT 0,
	"Name"	TEXT NOT NULL,
	"Password"	TEXT,
	"RoomType" INTEGER,
	"Settings"	TEXT,
	"Host"	TEXT NOT NULL,
	"CreationDate"	TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
	"History"	TEXT,
	PRIMARY KEY("PublicUrl","IsActive"),
	FOREIGN KEY("Host") REFERENCES "user"("UUID") ON UPDATE CASCADE
);
COMMIT;
