BEGIN TRANSACTION;
-- DROP TABLE room;
-- DROP TABLE user;
-- DROP TABLE room_member;
CREATE TABLE IF NOT EXISTS "room" (
	"PublicUrl"	TEXT NOT NULL UNIQUE,
	"IsActive"	INTEGER NOT NULL DEFAULT 0,
	"Name"	TEXT NOT NULL,
	"Password"	TEXT,
	"RoomType"	INTEGER,
	"Settings"	TEXT,
	"Host"	TEXT NOT NULL,
	"CreationDate"	TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
	"History"	TEXT,
	PRIMARY KEY("PublicUrl"),
	FOREIGN KEY("Host") REFERENCES "user"("UUID") ON UPDATE CASCADE
);
CREATE TABLE IF NOT EXISTS "user" (
	"UUID"	TEXT NOT NULL UNIQUE,
	"CreationDate"	TEXT DEFAULT CURRENT_TIMESTAMP,
	"LastSeenDate"	TEXT,
	"Name"	TEXT,
	"Avatar"	TEXT,
	PRIMARY KEY("UUID")
);
CREATE TABLE IF NOT EXISTS "room_member" (
	"RoomId"	TEXT NOT NULL,
	"UserId"	TEXT NOT NULL,
	"EnterDate"	TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
	"UserName"	TEXT,
	"UserAvatar"	TEXT,
	FOREIGN KEY("UserId") REFERENCES "user"("UUID") ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY("RoomId") REFERENCES "room"("PublicUrl") ON UPDATE CASCADE ON DELETE CASCADE,
	PRIMARY KEY("RoomId","UserId")
);
COMMIT;
